version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: cargo_admin
      POSTGRES_PASSWORD: cargo_password
      POSTGRES_DB: cargo_management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cargo_admin -d cargo_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://cargo_admin:cargo_password@db:5432/cargo_management
      - PYTHONPATH=/app

volumes:
  postgres_data:
